    apiVersion: v1
kind: Service
metadata:
  name: movie-catalog-service
  labels:
    app: movie-catalog
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: movie-catalog
